### ISSUE TITLE
IMAP

### ISSUE THREAD

**Issue by cwalkatron** [moriyoshi/cyrus-sasl-xoauth2#1]
I'm interested in using this to add `XOAUTH2` support to the `mutt` mailer. Have you tried using it with IMAP? Thanks for the work here. Is there any more documentation?

**Comment by moriyoshi** [comment]
Mutt seems to have its own authentication implementation which is not pluggable.  Although this project provides the client authentication module along with the server module,  I don't think the client module can be used with Mutt without modifying Mutt itself.

**Comment by moriyoshi** [comment]
Sorry, it was not quite right.  Take a look at the configuration in the following ticket: https://dev.mutt.org/trac/ticket/3921  It should work now.
