### ISSUE TITLE
FYI: Instructions for combining OAUTH2, fetchmail and postfix with gmail

### ISSUE THREAD

**Issue by mmogilvi** [moriyoshi/cyrus-sasl-xoauth2#2]
My $DAYJOB switched to using Google "G Suite" (hosted gmail for businesses), and it was configured to require the use of OAUTH2 authentication to send and receive email.  Webmail is terribly annoying, so I eventually put together a set of patches, scripts, this (cyrus-sasl-xoauth2) plugin, configuration options, etc to be able to **both send and receive** mail from my company gmail account with minimal manual effort (after it is setup).

In case it might benefit anyone else, I've documented it all at the following URL:
http://mmogilvi.users.sourceforge.net/software/oauthbearer.html

(This probably doesn't count as an "Issue", but I couldn't find a better place to mention this documentation.)

**Comment by moriyoshi** [comment]
That's gotta be helpful for everyone who is under the same circumstances!  I'm gonna add the link to the doc.  Thanks.
