### ISSUE TITLE
Contribute to cyrusimap/cyrus-sasl

### ISSUE THREAD

**Issue by stbischof** [moriyoshi/cyrus-sasl-xoauth2#5]
Hi @moriyoshi,

would you may add an PR of your cyrus-sasl-xoauth2-plugin to 
https://github.com/cyrusimap/cyrus-sasl

ref: https://github.com/cyrusimap/cyrus-sasl/issues/522

**Comment by moriyoshi** [comment]
Thanks for the heads-up.  There are several points worth a note:

1. The issue cyrusimap/cyrus-sasl#522 refers to RFC 7628, which describes a mechanism similar to XOAUTH2, but those are different in how to build the payload sent to the server.  `OAUTHBEARER` uses base64-encoded key-value pairs while XOAUTH2 uses base64-encoded JSONs.
2. Addition of XOAUTH2 to cyrus-sasl was discussed before on the list.
    https://lists.andrew.cmu.edu/pipermail/cyrus-sasl/2018-May/003132.html
    The key point is the client plugin needs some external mechanism that initiates initial token retrieval and subsequent token refreshment and it isn't standardized at the moment.
